highlighter: rouge
markdown: kramdown
url: http://www.thomasleeper.com/websurveycourse
author: Thomas J. Leeper
name: Web Survey Course
description: survey, experiment, survey experiment, online, web, mturk, mechanical turk, qualtrics, survey monkey, google forms
